"""ingredients and ingredient_conflicts tables

Revision ID: 7eeabf343e68
Revises: 
Create Date: 2026-04-21 20:24:48.357900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eeabf343e68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('before_after_food', sa.Enum('before', 'after', name='beforeafterfood'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_conflicts',
    sa.Column('id_a', sa.Integer(), nullable=False),
    sa.Column('id_b', sa.Integer(), nullable=False),
    sa.CheckConstraint('id_a != id_b', name='id_a_not_equal_to_id_b'),
    sa.CheckConstraint('id_a < id_b', name='id_a_less_than_id_b'),
    sa.ForeignKeyConstraint(['id_a'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_b'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_a', 'id_b')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_conflicts')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
