"""ingredient_name_unique_constraint

Revision ID: cc9be5dbeee2
Revises: 7eeabf343e68
Create Date: 2026-04-22 15:00:38.992145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9be5dbeee2'
down_revision: Union[str, Sequence[str], None] = '7eeabf343e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ingredient_name_unique', 'ingredients', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingredient_name_unique', 'ingredients', type_='unique')
    # ### end Alembic commands ###
